name: project-ci

on:
  push:
    branches:
      - dev

jobs:
  ci:
    strategy:
      fail-fast: false


    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Setup nodejs
        uses: actions/setup-node@v2


      - name: Download dependencies (at least 9000, because javascript)
        run: npm install

      - name: Run backend tests
        run: npm run test

      - name: Run frontend tests

        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:8080/docs'
